-- =============================================================================
--  EXAM PORTAL — PostgreSQL DDL  (v4 — Long ID)
--  Package : com.mss.exam.portal
--  Requires: PostgreSQL 15+
--  Naming  : ALL_CAPS tables & columns
--
--  Audit columns (BaseEntity):
--    CREATED_BY_USER_ID  → FK_<TABLE>_AUDIT_CREATED  → USERS(ID)
--    UPDATED_BY_USER_ID  → FK_<TABLE>_AUDIT_UPDATED  → USERS(ID)
--  These names are intentionally distinct from business-level CREATED_BY_ID
--  FKs (e.g. FK_COURSES_CREATED_BY) to prevent naming collisions.
-- =============================================================================


-- ─────────────────────────────────────────────────────────────────────────────
--  DROP — reverse dependency order (safe re-run)
-- ─────────────────────────────────────────────────────────────────────────────
DROP TABLE IF EXISTS SUBMISSION_FILES CASCADE;
DROP TABLE IF EXISTS ANSWERS CASCADE;
DROP TABLE IF EXISTS EXAM_ATTEMPTS CASCADE;
DROP TABLE IF EXISTS QUESTION_TAG_MAPPINGS CASCADE;
DROP TABLE IF EXISTS QUESTION_TAGS CASCADE;
DROP TABLE IF EXISTS PAYMENT_TRANSACTIONS CASCADE;
DROP TABLE IF EXISTS PAYMENTS CASCADE;
DROP TABLE IF EXISTS ENROLLMENTS CASCADE;
DROP TABLE IF EXISTS BATCH_EXAMS CASCADE;
DROP TABLE IF EXISTS BATCH_INSTRUCTORS CASCADE;
DROP TABLE IF EXISTS OPTIONS CASCADE;
DROP TABLE IF EXISTS QUESTIONS CASCADE;
DROP TABLE IF EXISTS SUBJECTS CASCADE;
DROP TABLE IF EXISTS EXAM_CONDUCTORS CASCADE;
DROP TABLE IF EXISTS EXAMS CASCADE;
DROP TABLE IF EXISTS BATCHES CASCADE;
DROP TABLE IF EXISTS COURSE_CATEGORY_MAPPINGS CASCADE;
DROP TABLE IF EXISTS COURSES CASCADE;
DROP TABLE IF EXISTS CATEGORIES CASCADE;
DROP TABLE IF EXISTS USER_FILES CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;


-- =============================================================================
--  1. USERS
--  Audit columns are plain BIGINT here (no FK) — USERS is the root table;
--  a self-referencing FK would cause a circular dependency on first INSERT.
-- =============================================================================
CREATE TABLE USERS
(
    ID         BIGSERIAL   NOT NULL,
    USERNAME           VARCHAR(50)  NOT NULL,
    EMAIL              VARCHAR(120) NOT NULL,
    PASSWORD_HASH      VARCHAR(255) NOT NULL,
    NAME       VARCHAR(80) NOT NULL,
    NAME_LOCAL VARCHAR(80) NOT NULL,
    PHONE              VARCHAR(20),
    ROLE               VARCHAR(30)  NOT NULL,
    IS_ACTIVE          BOOLEAN      NOT NULL DEFAULT TRUE,
    IS_DELETED         BOOLEAN      NOT NULL DEFAULT FALSE,
    CREATED_AT         TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT         TIMESTAMP,
    CREATED_BY_USER_ID BIGINT, -- no FK, root table
    UPDATED_BY_USER_ID BIGINT, -- no FK, root table

    CONSTRAINT PK_USERS PRIMARY KEY (ID),
    CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT CHK_USERS_ROLE CHECK (ROLE IN (
                                              'ROLE_ADMIN',
                                              'ROLE_INSTRUCTOR',
                                              'ROLE_EXAMINER',
                                              'ROLE_STUDENT'
        ))
);

CREATE INDEX IDX_USERS_EMAIL ON USERS (EMAIL);
CREATE INDEX IDX_USERS_ROLE ON USERS (ROLE);


-- =============================================================================
--  2. USER_FILES
-- =============================================================================
CREATE TABLE USER_FILES
(
    ID      BIGSERIAL NOT NULL,
    USER_ID BIGINT    NOT NULL,
    S3_OBJECT_KEY      VARCHAR(500) NOT NULL,
    FILE_URL           VARCHAR(500) NOT NULL,
    ORIGINAL_FILENAME  VARCHAR(255) NOT NULL,
    CONTENT_TYPE       VARCHAR(100) NOT NULL,
    FILE_SIZE_BYTES    BIGINT,
    FILE_TYPE          VARCHAR(30)  NOT NULL,
    IS_ACTIVE          BOOLEAN      NOT NULL DEFAULT TRUE,
    IS_DELETED         BOOLEAN      NOT NULL DEFAULT FALSE,
    CREATED_AT         TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT         TIMESTAMP,
    CREATED_BY_USER_ID BIGINT,
    UPDATED_BY_USER_ID BIGINT,

    CONSTRAINT PK_USER_FILES PRIMARY KEY (ID),
    CONSTRAINT FK_USER_FILES_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_USER_FILES_AUDIT_CREATED
        FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_USER_FILES_AUDIT_UPDATED
        FOREIGN KEY (UPDATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT CHK_USER_FILES_TYPE CHECK (FILE_TYPE IN (
                                                        'PROFILE_PICTURE',
                                                        'SUBMISSION_PDF',
                                                        'SUBMISSION_IMAGE',
                                                        'CERTIFICATE',
                                                        'EXAM_ATTACHMENT'
        ))
);

CREATE INDEX IDX_USER_FILES_USER_ID ON USER_FILES (USER_ID);
CREATE INDEX IDX_USER_FILES_FILE_TYPE ON USER_FILES (FILE_TYPE);
CREATE INDEX IDX_USER_FILES_IS_ACTIVE ON USER_FILES (IS_ACTIVE);


-- =============================================================================
--  3. CATEGORIES
-- =============================================================================
CREATE TABLE CATEGORIES
(
    ID                 BIGSERIAL    NOT NULL,
    NAME               VARCHAR(100) NOT NULL,
    NAME_LOCAL         VARCHAR(100) NOT NULL,
    DESCRIPTION        VARCHAR(500),
    DISPLAY_ORDER      INTEGER      NOT NULL DEFAULT 0,
    IS_ACTIVE          BOOLEAN      NOT NULL DEFAULT TRUE,
    IS_DELETED         BOOLEAN      NOT NULL DEFAULT FALSE,
    CREATED_AT         TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT         TIMESTAMP,
    CREATED_BY_USER_ID BIGINT,
    UPDATED_BY_USER_ID BIGINT,

    CONSTRAINT PK_CATEGORIES PRIMARY KEY (ID),
    CONSTRAINT UQ_CATEGORIES_NAME UNIQUE (NAME),
    CONSTRAINT FK_CATEGORIES_AUDIT_CREATED
        FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_CATEGORIES_AUDIT_UPDATED
        FOREIGN KEY (UPDATED_BY_USER_ID) REFERENCES USERS (ID)
);

CREATE INDEX IDX_CATEGORIES_NAME ON CATEGORIES (NAME);


-- =============================================================================
--  4. COURSES
-- =============================================================================
CREATE TABLE COURSES
(
    ID          BIGSERIAL    NOT NULL,
    TITLE              VARCHAR(200)   NOT NULL,
    TITLE_LOCAL VARCHAR(200) NOT NULL,
    CODE               VARCHAR(50)    NOT NULL,
    DESCRIPTION        TEXT,
    THUMBNAIL_URL      VARCHAR(500),
    COURSE_FEE         NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    IS_ACTIVE          BOOLEAN        NOT NULL DEFAULT TRUE,
    IS_DELETED         BOOLEAN        NOT NULL DEFAULT FALSE,
    CREATED_AT         TIMESTAMP      NOT NULL DEFAULT NOW(),
    UPDATED_AT         TIMESTAMP,
    CREATED_BY_USER_ID BIGINT,
    UPDATED_BY_USER_ID BIGINT,

    CONSTRAINT PK_COURSES PRIMARY KEY (ID),
    CONSTRAINT UQ_COURSES_CODE UNIQUE (CODE),
    CONSTRAINT FK_COURSES_AUDIT_CREATED
        FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_COURSES_AUDIT_UPDATED
        FOREIGN KEY (UPDATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT CHK_COURSES_FEE CHECK (COURSE_FEE >= 0)
);

CREATE INDEX IDX_COURSES_CODE ON COURSES (CODE);


-- =============================================================================
--  4.1 COURSE_CATEGORY_MAPPINGS (Many-to-Many join table)
-- =============================================================================
CREATE TABLE COURSE_CATEGORY_MAPPINGS
(
    CATEGORY_ID BIGINT NOT NULL,
    COURSE_ID   BIGINT NOT NULL,

    CONSTRAINT PK_COURSE_CATEGORY_MAPPINGS PRIMARY KEY (CATEGORY_ID, COURSE_ID),
    CONSTRAINT FK_COURSE_CATEGORY_MAPPINGS_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID),
    CONSTRAINT FK_COURSE_CATEGORY_MAPPINGS_COURSE FOREIGN KEY (COURSE_ID) REFERENCES COURSES (ID)
);

CREATE INDEX IDX_COURSE_CATEGORY_MAPPINGS_COURSE_ID ON COURSE_CATEGORY_MAPPINGS (COURSE_ID);


-- =============================================================================
--  5. BATCHES
-- =============================================================================
CREATE TABLE BATCHES
(
    ID         BIGSERIAL    NOT NULL,
    COURSE_ID  BIGINT       NOT NULL,
    NAME               VARCHAR(150)  NOT NULL,
    NAME_LOCAL VARCHAR(150) NOT NULL,
    CSV_FILENAME       VARCHAR(255)  NOT NULL,
    S3_OBJECT_KEY      VARCHAR(500),
    TOTAL_ROWS         INTEGER       NOT NULL DEFAULT 0,
    ENROLLED_COUNT     INTEGER       NOT NULL DEFAULT 0,
    FAILED_COUNT       INTEGER       NOT NULL DEFAULT 0,
    SKIPPED_COUNT      INTEGER       NOT NULL DEFAULT 0,
    DISCOUNT           NUMERIC(5, 2) NOT NULL DEFAULT 0.00,
    STATUS             VARCHAR(20)   NOT NULL DEFAULT 'UPLOADED',
    ERROR_LOG          TEXT,
    IS_DELETED         BOOLEAN       NOT NULL DEFAULT FALSE,
    CREATED_AT         TIMESTAMP     NOT NULL DEFAULT NOW(),
    UPDATED_AT         TIMESTAMP,
    CREATED_BY_USER_ID BIGINT,
    UPDATED_BY_USER_ID BIGINT,

    CONSTRAINT PK_BATCHES PRIMARY KEY (ID),
    CONSTRAINT FK_BATCHES_COURSE FOREIGN KEY (COURSE_ID) REFERENCES COURSES (ID),
    CONSTRAINT FK_BATCHES_AUDIT_CREATED
        FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_BATCHES_AUDIT_UPDATED
        FOREIGN KEY (UPDATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT CHK_BATCHES_STATUS CHECK (STATUS IN (
                                                    'UPLOADED',
                                                    'PROCESSING',
                                                    'COMPLETED',
                                                    'PARTIALLY_FAILED',
                                                    'FAILED'
        )),
    CONSTRAINT CHK_BATCHES_DISCOUNT CHECK (DISCOUNT >= 0 AND DISCOUNT <= 100)
);

CREATE INDEX IDX_BATCHES_COURSE_ID ON BATCHES (COURSE_ID);
CREATE INDEX IDX_BATCHES_STATUS ON BATCHES (STATUS);


-- =============================================================================
--  6. EXAMS
-- =============================================================================
CREATE TABLE EXAMS
(
    ID                 BIGSERIAL    NOT NULL,
    TITLE                      VARCHAR(200)   NOT NULL,
    TITLE_LOCAL        VARCHAR(200) NOT NULL,
    DESCRIPTION                TEXT,
    EXAM_TYPE                  VARCHAR(20)    NOT NULL,
    EXAM_START_TIME            TIME           NOT NULL,
    EXAM_END_TIME              TIME           NOT NULL,
    DURATION_MINUTES           INTEGER        NOT NULL,
    PASS_MARK_PERCENT          INTEGER        NOT NULL,
    TOTAL_MARKS                INTEGER        NOT NULL DEFAULT 0,
    MAX_ATTEMPTS               INTEGER        NOT NULL DEFAULT 1,
    IS_PUBLISHED               BOOLEAN        NOT NULL DEFAULT FALSE,
    IS_RANDOMIZE_QUESTIONS     BOOLEAN        NOT NULL DEFAULT FALSE,
    IS_SHOW_RESULT_IMMEDIATELY BOOLEAN        NOT NULL DEFAULT TRUE,
    ENROLLMENT_FEE             NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    CERTIFICATE_TEMPLATE_URL   VARCHAR(500),
    IS_DELETED                 BOOLEAN        NOT NULL DEFAULT FALSE,
    CREATED_AT                 TIMESTAMP      NOT NULL DEFAULT NOW(),
    UPDATED_AT                 TIMESTAMP,
    CREATED_BY_USER_ID BIGINT,
    UPDATED_BY_USER_ID BIGINT,

    CONSTRAINT PK_EXAMS PRIMARY KEY (ID),
    CONSTRAINT FK_EXAMS_AUDIT_CREATED
        FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_EXAMS_AUDIT_UPDATED
        FOREIGN KEY (UPDATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT CHK_EXAMS_EXAM_TYPE CHECK (EXAM_TYPE IN (
                                                        'MCQ', 'WRITTEN', 'MIXED', 'PROCTORED', 'TAKE_HOME'
        )),
    CONSTRAINT CHK_EXAMS_DURATION CHECK (DURATION_MINUTES BETWEEN 10 AND 600),
    CONSTRAINT CHK_EXAMS_PASS_MARK CHECK (PASS_MARK_PERCENT BETWEEN 0 AND 100),
    CONSTRAINT CHK_EXAMS_MAX_ATTEMPTS CHECK (MAX_ATTEMPTS >= 1),
    CONSTRAINT CHK_EXAMS_TIME_WINDOW CHECK (EXAM_END_TIME > EXAM_START_TIME)
);

CREATE INDEX IDX_EXAMS_EXAM_TYPE ON EXAMS (EXAM_TYPE);
CREATE INDEX IDX_EXAMS_START_TIME ON EXAMS (EXAM_START_TIME);


-- =============================================================================
--  6.1 EXAM_CONDUCTORS (Many-to-Many join table)
-- =============================================================================
CREATE TABLE EXAM_CONDUCTORS
(
    EXAM_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,

    CONSTRAINT PK_EXAM_CONDUCTORS PRIMARY KEY (EXAM_ID, USER_ID),
    CONSTRAINT FK_EXAM_CONDUCTORS_EXAM FOREIGN KEY (EXAM_ID) REFERENCES EXAMS (ID),
    CONSTRAINT FK_EXAM_CONDUCTORS_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE INDEX IDX_EXAM_CONDUCTORS_EXAM_ID ON EXAM_CONDUCTORS (EXAM_ID);
CREATE INDEX IDX_EXAM_CONDUCTORS_USER_ID ON EXAM_CONDUCTORS (USER_ID);


-- =============================================================================
--  7. BATCH_EXAMS (Many-to-Many join table)
-- =============================================================================
CREATE TABLE BATCH_EXAMS
(
    BATCH_ID BIGINT NOT NULL,
    EXAM_ID  BIGINT NOT NULL,

    CONSTRAINT PK_BATCH_EXAMS PRIMARY KEY (BATCH_ID, EXAM_ID),
    CONSTRAINT FK_BATCH_EXAMS_BATCH FOREIGN KEY (BATCH_ID) REFERENCES BATCHES (ID),
    CONSTRAINT FK_BATCH_EXAMS_EXAM FOREIGN KEY (EXAM_ID) REFERENCES EXAMS (ID)
);

CREATE INDEX IDX_BATCH_EXAMS_BATCH_ID ON BATCH_EXAMS (BATCH_ID);
CREATE INDEX IDX_BATCH_EXAMS_EXAM_ID ON BATCH_EXAMS (EXAM_ID);


-- =============================================================================
--  7.1 BATCH_INSTRUCTORS (Many-to-Many join table)
-- =============================================================================
CREATE TABLE BATCH_INSTRUCTORS
(
    BATCH_ID BIGINT NOT NULL,
    USER_ID  BIGINT NOT NULL,

    CONSTRAINT PK_BATCH_INSTRUCTORS PRIMARY KEY (BATCH_ID, USER_ID),
    CONSTRAINT FK_BATCH_INSTRUCTORS_BATCH FOREIGN KEY (BATCH_ID) REFERENCES BATCHES (ID),
    CONSTRAINT FK_BATCH_INSTRUCTORS_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);

CREATE INDEX IDX_BATCH_INSTRUCTORS_BATCH_ID ON BATCH_INSTRUCTORS (BATCH_ID);
CREATE INDEX IDX_BATCH_INSTRUCTORS_USER_ID ON BATCH_INSTRUCTORS (USER_ID);


-- =============================================================================
--  7. SUBJECTS
-- =============================================================================
CREATE TABLE SUBJECTS
(
    ID                 BIGSERIAL    NOT NULL,
    NAME               VARCHAR(150) NOT NULL,
    DESCRIPTION        VARCHAR(500),
    DISPLAY_ORDER      INTEGER      NOT NULL DEFAULT 0,
    IS_ACTIVE          BOOLEAN      NOT NULL DEFAULT TRUE,
    IS_DELETED         BOOLEAN      NOT NULL DEFAULT FALSE,
    CREATED_AT         TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT         TIMESTAMP,
    CREATED_BY_USER_ID BIGINT,
    UPDATED_BY_USER_ID BIGINT,

    CONSTRAINT PK_SUBJECTS PRIMARY KEY (ID),
    CONSTRAINT UQ_SUBJECTS_NAME UNIQUE (NAME),
    CONSTRAINT FK_SUBJECTS_AUDIT_CREATED
        FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_SUBJECTS_AUDIT_UPDATED
        FOREIGN KEY (UPDATED_BY_USER_ID) REFERENCES USERS (ID)
);

CREATE INDEX IDX_SUBJECTS_NAME ON SUBJECTS (NAME);


-- =============================================================================
--  8. QUESTIONS
-- =============================================================================
CREATE TABLE QUESTIONS
(
    ID            BIGSERIAL NOT NULL,
    CATEGORY_ID   BIGINT,
    SUBJECT_ID    BIGINT,
    EXAM_ID       BIGINT    NOT NULL,
    QUESTION_TEXT      TEXT        NOT NULL,
    QUESTION_TYPE      VARCHAR(20) NOT NULL,
    MARKS              INTEGER     NOT NULL DEFAULT 1,
    ORDER_NO           INTEGER     NOT NULL DEFAULT 0,
    EXPLANATION        TEXT,
    ANSWER_KEYWORDS    TEXT,
    IMAGE_URL          VARCHAR(500),
    IS_MANDATORY       BOOLEAN     NOT NULL DEFAULT TRUE,
    QUESTION_YEAR INTEGER,
    IS_DELETED         BOOLEAN     NOT NULL DEFAULT FALSE,
    CREATED_AT         TIMESTAMP   NOT NULL DEFAULT NOW(),
    UPDATED_AT         TIMESTAMP,
    CREATED_BY_USER_ID BIGINT,
    UPDATED_BY_USER_ID BIGINT,

    CONSTRAINT PK_QUESTIONS PRIMARY KEY (ID),
    CONSTRAINT FK_QUESTIONS_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES (ID),
    CONSTRAINT FK_QUESTIONS_SUBJECT FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID),
    CONSTRAINT FK_QUESTIONS_EXAM FOREIGN KEY (EXAM_ID) REFERENCES EXAMS (ID),
    CONSTRAINT FK_QUESTIONS_AUDIT_CREATED
        FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_QUESTIONS_AUDIT_UPDATED
        FOREIGN KEY (UPDATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT CHK_QUESTIONS_TYPE CHECK (QUESTION_TYPE IN (
                                                           'SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'TRUE_FALSE',
                                                           'SHORT_ANSWER', 'LONG_ANSWER'
        )),
    CONSTRAINT CHK_QUESTIONS_MARKS CHECK (MARKS >= 1)
);

CREATE INDEX IDX_QUESTIONS_EXAM_ID ON QUESTIONS (EXAM_ID);
CREATE INDEX IDX_QUESTIONS_CATEGORY_ID ON QUESTIONS (CATEGORY_ID);
CREATE INDEX IDX_QUESTIONS_SUBJECT_ID ON QUESTIONS (SUBJECT_ID);
CREATE INDEX IDX_QUESTIONS_ORDER_NO ON QUESTIONS (ORDER_NO);


-- =============================================================================
--  8.1 QUESTION_TAGS
-- =============================================================================
CREATE TABLE QUESTION_TAGS
(
    ID                 BIGSERIAL   NOT NULL,
    NAME               VARCHAR(50) NOT NULL,
    NAME_LOCAL         VARCHAR(50) NOT NULL,
    COLOR              VARCHAR(7),
    IS_DELETED         BOOLEAN     NOT NULL DEFAULT FALSE,
    CREATED_AT         TIMESTAMP   NOT NULL DEFAULT NOW(),
    UPDATED_AT         TIMESTAMP,
    CREATED_BY_USER_ID BIGINT,
    UPDATED_BY_USER_ID BIGINT,

    CONSTRAINT PK_QUESTION_TAGS PRIMARY KEY (ID),
    CONSTRAINT UQ_QUESTION_TAGS_NAME UNIQUE (NAME),
    CONSTRAINT UQ_QUESTION_TAGS_NAME_LOCAL UNIQUE (NAME_LOCAL),
    CONSTRAINT FK_QUESTION_TAGS_AUDIT_CREATED
        FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_QUESTION_TAGS_AUDIT_UPDATED
        FOREIGN KEY (UPDATED_BY_USER_ID) REFERENCES USERS (ID)
);

CREATE INDEX IDX_QUESTION_TAGS_NAME ON QUESTION_TAGS (NAME);


-- =============================================================================
--  8.2 QUESTION_TAG_MAPPINGS (Many-to-Many join table)
-- =============================================================================
CREATE TABLE QUESTION_TAG_MAPPINGS
(
    QUESTION_ID BIGINT NOT NULL,
    TAG_ID      BIGINT NOT NULL,

    CONSTRAINT PK_QUESTION_TAG_MAPPINGS PRIMARY KEY (QUESTION_ID, TAG_ID),
    CONSTRAINT FK_QUESTION_TAG_MAPPINGS_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS (ID),
    CONSTRAINT FK_QUESTION_TAG_MAPPINGS_TAG FOREIGN KEY (TAG_ID) REFERENCES QUESTION_TAGS (ID)
);

CREATE INDEX IDX_QUESTION_TAG_MAPPINGS_TAG_ID ON QUESTION_TAG_MAPPINGS (TAG_ID);


-- =============================================================================
--  9. OPTIONS
-- =============================================================================
CREATE TABLE OPTIONS
(
    ID                 BIGSERIAL NOT NULL,
    QUESTION_ID        BIGINT    NOT NULL,
    OPTION_TEXT        TEXT      NOT NULL,
    IS_CORRECT         BOOLEAN   NOT NULL DEFAULT FALSE,
    DISPLAY_ORDER      INTEGER   NOT NULL DEFAULT 0,
    IMAGE_URL          VARCHAR(500),
    IS_DELETED         BOOLEAN   NOT NULL DEFAULT FALSE,
    CREATED_AT         TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT         TIMESTAMP,
    CREATED_BY_USER_ID BIGINT,
    UPDATED_BY_USER_ID BIGINT,

    CONSTRAINT PK_OPTIONS PRIMARY KEY (ID),
    CONSTRAINT FK_OPTIONS_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS (ID),
    CONSTRAINT FK_OPTIONS_AUDIT_CREATED
        FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_OPTIONS_AUDIT_UPDATED
        FOREIGN KEY (UPDATED_BY_USER_ID) REFERENCES USERS (ID)
);

CREATE INDEX IDX_OPTIONS_QUESTION_ID ON OPTIONS (QUESTION_ID);


-- =============================================================================
--  10. ENROLLMENTS
-- =============================================================================
CREATE TABLE ENROLLMENTS
(
    ID         BIGSERIAL NOT NULL,
    STUDENT_ID BIGINT    NOT NULL,
    EXAM_ID    BIGINT    NOT NULL,
    BATCH_ID           BIGINT,
    STATUS             VARCHAR(25) NOT NULL DEFAULT 'PENDING_PAYMENT',
    ATTEMPTS_USED      INTEGER     NOT NULL DEFAULT 0,
    ENROLLED_AT        TIMESTAMP,
    EXPIRES_AT         TIMESTAMP,
    IS_FEE_WAIVED      BOOLEAN     NOT NULL DEFAULT FALSE,
    IS_DELETED         BOOLEAN     NOT NULL DEFAULT FALSE,
    CREATED_AT         TIMESTAMP   NOT NULL DEFAULT NOW(),
    UPDATED_AT         TIMESTAMP,
    CREATED_BY_USER_ID BIGINT,
    UPDATED_BY_USER_ID BIGINT,

    CONSTRAINT PK_ENROLLMENTS PRIMARY KEY (ID),
    CONSTRAINT UQ_ENROLLMENT_STUDENT_EXAM UNIQUE (STUDENT_ID, EXAM_ID),
    CONSTRAINT FK_ENROLLMENTS_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_ENROLLMENTS_EXAM FOREIGN KEY (EXAM_ID) REFERENCES EXAMS (ID),
    CONSTRAINT FK_ENROLLMENTS_BATCH FOREIGN KEY (BATCH_ID) REFERENCES BATCHES (ID),
    CONSTRAINT FK_ENROLLMENTS_AUDIT_CREATED
        FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_ENROLLMENTS_AUDIT_UPDATED
        FOREIGN KEY (UPDATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT CHK_ENROLLMENTS_STATUS CHECK (STATUS IN (
                                                        'PENDING_PAYMENT', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'EXPIRED'
        )),
    CONSTRAINT CHK_ENROLLMENTS_ATTEMPTS CHECK (ATTEMPTS_USED >= 0)
);

CREATE INDEX IDX_ENROLLMENTS_STUDENT_ID ON ENROLLMENTS (STUDENT_ID);
CREATE INDEX IDX_ENROLLMENTS_EXAM_ID ON ENROLLMENTS (EXAM_ID);
CREATE INDEX IDX_ENROLLMENTS_BATCH_ID ON ENROLLMENTS (BATCH_ID);
CREATE INDEX IDX_ENROLLMENTS_STATUS ON ENROLLMENTS (STATUS);


-- =============================================================================
--  11. PAYMENTS
-- =============================================================================
CREATE TABLE PAYMENTS
(
    ID            BIGSERIAL NOT NULL,
    ENROLLMENT_ID BIGINT    NOT NULL,
    AMOUNT_DUE         NUMERIC(10, 2) NOT NULL,
    AMOUNT_PAID        NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    CURRENCY           VARCHAR(3)     NOT NULL DEFAULT 'USD',
    STATUS             VARCHAR(20)    NOT NULL DEFAULT 'UNPAID',
    NOTES              TEXT,
    IS_DELETED         BOOLEAN        NOT NULL DEFAULT FALSE,
    CREATED_AT         TIMESTAMP      NOT NULL DEFAULT NOW(),
    UPDATED_AT         TIMESTAMP,
    CREATED_BY_USER_ID BIGINT,
    UPDATED_BY_USER_ID BIGINT,

    CONSTRAINT PK_PAYMENTS PRIMARY KEY (ID),
    CONSTRAINT UQ_PAYMENTS_ENROLLMENT UNIQUE (ENROLLMENT_ID),
    CONSTRAINT FK_PAYMENTS_ENROLLMENT FOREIGN KEY (ENROLLMENT_ID) REFERENCES ENROLLMENTS (ID),
    CONSTRAINT FK_PAYMENTS_AUDIT_CREATED
        FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_PAYMENTS_AUDIT_UPDATED
        FOREIGN KEY (UPDATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT CHK_PAYMENTS_STATUS CHECK (STATUS IN (
                                                     'UNPAID', 'PARTIALLY_PAID', 'PAID', 'REFUNDED', 'CANCELLED'
        )),
    CONSTRAINT CHK_PAYMENTS_AMOUNT_DUE CHECK (AMOUNT_DUE >= 0),
    CONSTRAINT CHK_PAYMENTS_AMOUNT_PAID CHECK (AMOUNT_PAID >= 0)
);

CREATE INDEX IDX_PAYMENTS_ENROLLMENT_ID ON PAYMENTS (ENROLLMENT_ID);
CREATE INDEX IDX_PAYMENTS_STATUS ON PAYMENTS (STATUS);


-- =============================================================================
--  12. PAYMENT_TRANSACTIONS
-- =============================================================================
CREATE TABLE PAYMENT_TRANSACTIONS
(
    ID                 BIGSERIAL NOT NULL,
    PAYMENT_ID         BIGINT    NOT NULL,
    STRIPE_CHARGE_ID         VARCHAR(100),
    STRIPE_PAYMENT_INTENT_ID VARCHAR(100),
    STRIPE_REFUND_ID         VARCHAR(100),
    AMOUNT                   NUMERIC(10, 2) NOT NULL,
    CURRENCY                 VARCHAR(3)     NOT NULL DEFAULT 'USD',
    STATUS                   VARCHAR(20)    NOT NULL DEFAULT 'PENDING',
    PAYMENT_METHOD           VARCHAR(50),
    PAYMENT_METHOD_DETAIL    VARCHAR(100),
    TRANSACTED_AT            TIMESTAMP,
    FAILURE_REASON           VARCHAR(255),
    WEBHOOK_PAYLOAD          TEXT,
    IS_DELETED               BOOLEAN        NOT NULL DEFAULT FALSE,
    CREATED_AT               TIMESTAMP      NOT NULL DEFAULT NOW(),
    UPDATED_AT               TIMESTAMP,
    CREATED_BY_USER_ID BIGINT,
    UPDATED_BY_USER_ID BIGINT,

    CONSTRAINT PK_PAYMENT_TRANSACTIONS PRIMARY KEY (ID),
    CONSTRAINT FK_PAY_TXN_PAYMENT FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENTS (ID),
    CONSTRAINT FK_PAY_TXN_AUDIT_CREATED
        FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_PAY_TXN_AUDIT_UPDATED
        FOREIGN KEY (UPDATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT CHK_PAY_TXN_STATUS CHECK (STATUS IN (
                                                    'PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'REFUNDED',
                                                    'CANCELLED'
        )),
    CONSTRAINT CHK_PAY_TXN_AMOUNT CHECK (AMOUNT >= 0)
);

CREATE INDEX IDX_PAY_TXN_PAYMENT_ID ON PAYMENT_TRANSACTIONS (PAYMENT_ID);
CREATE INDEX IDX_PAY_TXN_STATUS ON PAYMENT_TRANSACTIONS (STATUS);
CREATE INDEX IDX_PAY_TXN_STRIPE_CHARGE ON PAYMENT_TRANSACTIONS (STRIPE_CHARGE_ID);
CREATE INDEX IDX_PAY_TXN_TRANSACTED_AT ON PAYMENT_TRANSACTIONS (TRANSACTED_AT);


-- =============================================================================
--  13. EXAM_ATTEMPTS
-- =============================================================================
CREATE TABLE EXAM_ATTEMPTS
(
    ID                 BIGSERIAL NOT NULL,
    ENROLLMENT_ID      BIGINT    NOT NULL,
    EXAM_ID            BIGINT    NOT NULL,
    ATTEMPT_NUMBER     INTEGER   NOT NULL,
    STARTED_AT         TIMESTAMP NOT NULL,
    SUBMITTED_AT       TIMESTAMP,
    SCORE              INTEGER,
    SCORE_PERCENT      DOUBLE PRECISION,
    PASSED             BOOLEAN,
    IS_SUBMITTED       BOOLEAN   NOT NULL DEFAULT FALSE,
    IS_GRADED          BOOLEAN   NOT NULL DEFAULT FALSE,
    IP_ADDRESS         VARCHAR(45),
    CERTIFICATE_URL    VARCHAR(500),
    VERSION            BIGINT    NOT NULL DEFAULT 0,
    IS_DELETED         BOOLEAN   NOT NULL DEFAULT FALSE,
    CREATED_AT         TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT         TIMESTAMP,
    CREATED_BY_USER_ID BIGINT,
    UPDATED_BY_USER_ID BIGINT,

    CONSTRAINT PK_EXAM_ATTEMPTS PRIMARY KEY (ID),
    CONSTRAINT FK_EXAM_ATTEMPTS_ENROLLMENT FOREIGN KEY (ENROLLMENT_ID) REFERENCES ENROLLMENTS (ID),
    CONSTRAINT FK_EXAM_ATTEMPTS_EXAM FOREIGN KEY (EXAM_ID) REFERENCES EXAMS (ID),
    CONSTRAINT FK_EXAM_ATTEMPTS_AUDIT_CREATED
        FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_EXAM_ATTEMPTS_AUDIT_UPDATED
        FOREIGN KEY (UPDATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT CHK_EXAM_ATTEMPTS_NUMBER CHECK (ATTEMPT_NUMBER >= 1),
    CONSTRAINT CHK_EXAM_ATTEMPTS_SCORE_PCT CHECK (SCORE_PERCENT IS NULL OR SCORE_PERCENT BETWEEN 0 AND 100)
);

CREATE INDEX IDX_EXAM_ATTEMPTS_ENROLLMENT_ID ON EXAM_ATTEMPTS (ENROLLMENT_ID);
CREATE INDEX IDX_EXAM_ATTEMPTS_EXAM_ID ON EXAM_ATTEMPTS (EXAM_ID);
CREATE INDEX IDX_EXAM_ATTEMPTS_STARTED_AT ON EXAM_ATTEMPTS (STARTED_AT);


-- =============================================================================
--  14. ANSWERS
-- =============================================================================
CREATE TABLE ANSWERS
(
    ID                 BIGSERIAL NOT NULL,
    ATTEMPT_ID         BIGINT    NOT NULL,
    QUESTION_ID        BIGINT    NOT NULL,
    SELECTED_OPTION_ID BIGINT,
    TEXT_ANSWER        TEXT,
    MARKS_AWARDED      INTEGER,
    IS_CORRECT         BOOLEAN,
    EXAMINER_FEEDBACK  TEXT,
    IS_FLAGGED         BOOLEAN   NOT NULL DEFAULT FALSE,
    IS_DELETED         BOOLEAN   NOT NULL DEFAULT FALSE,
    CREATED_AT         TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT         TIMESTAMP,
    CREATED_BY_USER_ID BIGINT,
    UPDATED_BY_USER_ID BIGINT,

    CONSTRAINT PK_ANSWERS PRIMARY KEY (ID),
    CONSTRAINT UQ_ANSWERS_ATTEMPT_QUESTION UNIQUE (ATTEMPT_ID, QUESTION_ID),
    CONSTRAINT FK_ANSWERS_ATTEMPT FOREIGN KEY (ATTEMPT_ID) REFERENCES EXAM_ATTEMPTS (ID),
    CONSTRAINT FK_ANSWERS_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES QUESTIONS (ID),
    CONSTRAINT FK_ANSWERS_OPTION FOREIGN KEY (SELECTED_OPTION_ID) REFERENCES OPTIONS (ID),
    CONSTRAINT FK_ANSWERS_AUDIT_CREATED
        FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_ANSWERS_AUDIT_UPDATED
        FOREIGN KEY (UPDATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT CHK_ANSWERS_MARKS CHECK (MARKS_AWARDED IS NULL OR MARKS_AWARDED >= 0)
);

CREATE INDEX IDX_ANSWERS_ATTEMPT_ID ON ANSWERS (ATTEMPT_ID);
CREATE INDEX IDX_ANSWERS_QUESTION_ID ON ANSWERS (QUESTION_ID);


-- =============================================================================
--  15. SUBMISSION_FILES
-- =============================================================================
CREATE TABLE SUBMISSION_FILES
(
    ID         BIGSERIAL NOT NULL,
    ANSWER_ID  BIGINT    NOT NULL,
    ATTEMPT_ID BIGINT    NOT NULL,
    S3_OBJECT_KEY      VARCHAR(500) NOT NULL,
    FILE_URL           VARCHAR(500) NOT NULL,
    ORIGINAL_FILENAME  VARCHAR(255) NOT NULL,
    CONTENT_TYPE       VARCHAR(100) NOT NULL,
    FILE_SIZE_BYTES    BIGINT,
    FILE_TYPE          VARCHAR(30)  NOT NULL,
    PAGE_NUMBER        INTEGER      NOT NULL DEFAULT 1,
    IS_REVIEWED        BOOLEAN      NOT NULL DEFAULT FALSE,
    THUMBNAIL_URL      VARCHAR(500),
    IS_DELETED         BOOLEAN      NOT NULL DEFAULT FALSE,
    CREATED_AT         TIMESTAMP    NOT NULL DEFAULT NOW(),
    UPDATED_AT         TIMESTAMP,
    CREATED_BY_USER_ID BIGINT,
    UPDATED_BY_USER_ID BIGINT,

    CONSTRAINT PK_SUBMISSION_FILES PRIMARY KEY (ID),
    CONSTRAINT FK_SUB_FILES_ANSWER FOREIGN KEY (ANSWER_ID) REFERENCES ANSWERS (ID),
    CONSTRAINT FK_SUB_FILES_ATTEMPT FOREIGN KEY (ATTEMPT_ID) REFERENCES EXAM_ATTEMPTS (ID),
    CONSTRAINT FK_SUB_FILES_AUDIT_CREATED
        FOREIGN KEY (CREATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT FK_SUB_FILES_AUDIT_UPDATED
        FOREIGN KEY (UPDATED_BY_USER_ID) REFERENCES USERS (ID),
    CONSTRAINT CHK_SUB_FILES_TYPE CHECK (FILE_TYPE IN (
                                                       'PROFILE_PICTURE', 'SUBMISSION_PDF', 'SUBMISSION_IMAGE',
                                                       'CERTIFICATE', 'EXAM_ATTACHMENT'
        )),
    CONSTRAINT CHK_SUB_FILES_PAGE CHECK (PAGE_NUMBER >= 1),
    CONSTRAINT CHK_SUB_FILES_SIZE CHECK (FILE_SIZE_BYTES IS NULL OR FILE_SIZE_BYTES > 0)
);

CREATE INDEX IDX_SUB_FILES_ANSWER_ID ON SUBMISSION_FILES (ANSWER_ID);
CREATE INDEX IDX_SUB_FILES_ATTEMPT_ID ON SUBMISSION_FILES (ATTEMPT_ID);
CREATE INDEX IDX_SUB_FILES_FILE_TYPE ON SUBMISSION_FILES (FILE_TYPE);


-- =============================================================================
--  END OF SCHEMA
-- =============================================================================
