ALTER TABLE questions
    ADD COLUMN IF NOT EXISTS QUESTION_YEAR INTEGER DEFAULT NULL;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING';

ALTER TABLE users
    DROP COLUMN IF EXISTS IS_ACTIVE;

ALTER TABLE users
    ADD CONSTRAINT CHK_USERS_STATUS
        CHECK (STATUS IN ('PENDING', 'ACTIVE', 'INACTIVE', 'TERMINATED'));

-- Add geo columns to users
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS DIVISION_ID BIGINT;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS DISTRICT_ID BIGINT;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS UPAZILA_ID BIGINT;

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_DIVISION
        FOREIGN KEY (DIVISION_ID) REFERENCES DIVISIONS (DIVISION_ID);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_DISTRICT
        FOREIGN KEY (DISTRICT_ID) REFERENCES DISTRICTS (DISTRICT_ID);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_UPAZILA
        FOREIGN KEY (UPAZILA_ID) REFERENCES UPAZILAS (UPAZILA_ID);

-- Add indexes for NAME_LOCAL on geo tables
CREATE INDEX IF NOT EXISTS IDX_DIVISIONS_NAME_LOCAL ON DIVISIONS (NAME_LOCAL);
CREATE INDEX IF NOT EXISTS IDX_DISTRICTS_NAME_LOCAL ON DISTRICTS (NAME_LOCAL);
CREATE INDEX IF NOT EXISTS IDX_UPAZILAS_NAME_LOCAL ON UPAZILAS (NAME_LOCAL); 