ALTER TABLE questions
    ADD COLUMN IF NOT EXISTS QUESTION_YEAR INTEGER DEFAULT NULL;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING';

ALTER TABLE users
    DROP COLUMN IF EXISTS IS_ACTIVE;

ALTER TABLE users
    ADD CONSTRAINT CHK_USERS_STATUS
        CHECK (STATUS IN ('PENDING', 'ACTIVE', 'INACTIVE', 'TERMINATED')); 